---
name: build and publish docker container
on:
  push:
    branches:
      - master
    pull_request:
      branches:
        - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --project-name=vx-labs/wasp
      - name: Build and push Docker container
        uses: docker/build-push-action@v1
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          repository: vxlabs/wasp
          tags: "latest,${{ github.sha }}"
      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: "vxlabs/wasp:${{ github.sha }}"
          command: monitor
          args: --project-name=vx-labs/wasp